apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: url-shortener
  labels: { app: shell }
spec:
  selector: { app: shell }
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: url-shortener
  labels: { app: shell }
spec:
  replicas: 1
  selector:
    matchLabels: { app: shell }
  template:
    metadata:
      labels: { app: shell }
    spec:
      containers:
        - name: nginx
          image: url-shortener/shell:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
